### ISSUE TITLE
missing libmints?

### ISSUE THREAD

**Issue by jeiros** [rmcgibbo/resp2#4]
Hi,

I've installed psi4 with anaconda as instructed from their website and manually installed nlopt following the instructions in their [repo](https://github.com/stevengj/nlopt).

Running `make` after `./configure` on this repo is giving me the following error:
```
g++ -DHAVE_GDMA -DHAVE_DKH -DHAVE_MM_MALLOC_H -DHAS_CXX11_VARIADIC_TEMPLATES -DHAS_CXX11_STATIC_ASSERT -DHAS_CXX11_SIZEOF_MEMBER -DHAS_CXX11_RVALUE_REFERENCES -DHAS_CXX11_NULLPTR -DHAS_CXX11_LONG_LONG -DHAS_CXX11_LAMBDA -DHAS_CXX11_INITIALIZER_LIST -DHAS_CXX11_DECLTYPE -DHAS_CXX11_CSTDINT_H -DHAS_CXX11_CONSTEXPR -DHAS_CXX11_AUTO_RET_TYPE -DHAS_CXX11_AUTO -DHAS_CXX11_FUNC -DHAS_CXX11 -DSYS_LINUX -DUSE_FCMANGLE_H -D_GLIBCXX_USE_CXX11_ABI=0 -DRESTRICT=__restrict__ -fPIC -std=c++11 -Wno-deprecated-declarations -Iinclude -I/home/je714/psi4conda/bin/../include/ -I/home/je714/psi4conda/bin/../include/psi4 -I/home/je714/psi4conda/bin/../include/python2.7/  -c src/vdwsurface.cc -o obj/vdwsurface.o
In file included from src/vdwsurface.cc:14:0:
include/dotsphere.h:5:30: fatal error: libmints/vector3.h: No such file or directory
 #include "libmints/vector3.h"
                              ^
compilation terminated.
make: *** [obj/vdwsurface.o] Error 1
```
Is that part of nlopt or something else?

Thanks for any comments.

**Comment by leeping** [comment]
I don't know what's going on, as vector3.h does seem to be part of the current version of libmints. See https://github.com/psi4/psi4/blob/master/psi4/src/psi4/libmints/vector3.h

**Comment by jeiros** [comment]
I installed psi4 with their Linux [installer](http://psicode.org/downloads.html). As well as gcc and boost with anaconda.

**Comment by leeping** [comment]
I think the issue may be due to the `g++` command line not properly including the folder with `vector3.h`.  Can you experiment and see whether any other include flags (e.g. `-I/path/to/folder/with/vector3.h`) resolves the issue?  If so, then adding the include flag in the appropriate place in `setup.py` would allow the installation to complete.

**Comment by jeiros** [comment]
Hmmm... Using the psi4 installer script, the following line is appended to the `~/.bashrc` file: `export PATH=/home/je714/psi4conda/bin:$PATH` which I think is hiding the other conda environments? Since doing `conda info -e` gives the following:
```
# conda environments:
#
root                  *  /home/je714/psi4conda
```
Maybe that's why?

**Comment by leeping** [comment]
Yeah, installing psi4 with their installer will do that.  I think compiling Psi4 from source allows you to use your own Python environment, but it's been a while since I've done that. @yudongqiu recently installed it on our cluster and he may know more.

**Comment by rmcgibbo** [comment]
The Psi build system has been totally rewritten since the last time I touched this code. You probably need to rewrite the build system to work with Psi4-1.0 or later.

**Comment by jeiros** [comment]
Ouch. Fair enough 😄 I know this repo hasn't had much activity in some time. I'll see what I can do. Thanks for answering!
